site_name: Galaxy Lightcone
nav:  
	- Home:  index.md  
	- About:  about.md
	- Building the lightcone: building_lightcone.md
	- Data products: data_products.md
theme:  readthedocs


<!--stackedit_data:
eyJoaXN0b3J5IjpbLTE1MTAwMzE1MTgsLTExOTk5ODYyOThdfQ
==
-->